chat/urls.py
from django.urls import path
# from shortuuidfield import ShortUUIDField

from . import views 


urlpatterns = [
    path('',views.lobby),
    path('list/',views.listUsers),
    path('listchatrooms/',views.listChatrooms),
    path('createchatroom/<int:pk>',views.createChatRoom, name='create_chatroom'),
    path('getchatroom/<str:chatUuid>',views.getChatRoom, name='get_chatroom'),
    # createMessage

]

restft/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restApp.urls')),
    path('chat/',include(('chat.urls', 'chat'), namespace='chat'))
]

chat/models.py
from django.db import models
from django.dispatch import receiver
from shortuuidfield import ShortUUIDField
# from users.models import User
from django.contrib.auth.models import User
# Create your models here.
2

class ChatRoom(models.Model):
    chatUuid = ShortUUIDField(primary_key = True)
    # chatRoomName = models.CharField(max_length=225)
    user1 = models.ForeignKey(User,null=True,default=None,related_name='user1', on_delete=models.CASCADE)
    user2 = models.ForeignKey(User,null=True,default=None, related_name='user2', on_delete=models.CASCADE)

    def __str__(self):
        # return str(self.user1.username)+" and "+str(self.user2.username)
        return str(self.chatUuid)

class Message(models.Model):
    time = models.DateTimeField(auto_now=True)
    chatRoom =  models.ForeignKey('ChatRoom', on_delete=models.CASCADE)
    sender = models.ForeignKey(User,null=True,default=None, on_delete=models.CASCADE)
    message = models.CharField(max_length=225)

chat/views.py
import re
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.urls import reverse
from pyparsing import Or
from .models import ChatRoom,Message
# Create your views here.
def lobby(request):
    return render(request, 'chat/lobby.html',{})


def listUsers(request):
    objs = User.objects.all().exclude(username = request.user)
    context = {
        'objs':objs
    }
    print(objs)
    return render(request,'chat/list.html',context)


def listChatrooms(request):
    objs = ChatRoom.objects.all()
    required_chatrooms = objs.filter(user1 = request.user) | objs.filter(user2 = request.user)
    context = {
        'objs':required_chatrooms
    }
    return render(request,'chat/chatrooms.html',context)

def getChatRoom(request,chatUuid):
    obj = ChatRoom.objects.get(chatUuid = chatUuid)
    if obj.user1 != request.user:
        recvr = obj.user1
    elif obj.user2 != request.user:
        recvr = obj.user2
    # chats = []
    chats = Message.objects.filter(chatRoom_id = chatUuid)
    print("chats: ",chats)
    context = {
        'obj':obj,
        'personobj' : recvr,
        'chats':chats
    }
    return render(request,'chat/chat.html',context)

def createChatRoom(request, pk, format=None):
    print("pk --> ",pk)

    user1_obj = User.objects.get(username = request.user) # current logged in user
    user2_obj = User.objects.get(pk = pk) #selected chat

    filtereddata = ChatRoom.objects.filter(user1=user1_obj) | ChatRoom.objects.filter(user1=user2_obj) | ChatRoom.objects.filter(user2=user1_obj) | ChatRoom.objects.filter(user2=user2_obj)
    # print("filtered data: ",filtereddata)
    check = (filtereddata.filter(user1 = user1_obj) & filtereddata.filter(user2 = user2_obj)) | filtereddata.filter(user1 = user2_obj) & filtereddata.filter(user2 = user1_obj)
    # print("check if chatroom exists for the 2 users : ",check)
    if len(check) == 0:
        chatroomcreated = ChatRoom.objects.create(
                    user1 = user1_obj,
                    user2 = user2_obj
                )
        print("uuid: "+chatroomcreated.chatUuid)
        print("New ChatRoom Created")
    # print(chatroom)
        # return redirect(reverse('chat:get_chatroom', kwargs={'chatUuid':chatroomcreated.chatUuid}))    
        return redirect('/chat/getchatroom/'+chatroomcreated.chatUuid) #this works
    else:
        print("check: ",check)
        chaturl = check.first()
        print("chatUrl: ",chaturl)
        return redirect('/chat/getchatroom/'+str(chaturl)) #this works
    return render(request,'chat/list.html',{})




    

chat/templates/chat/chat.html
{% extends 'chat/lobby.html' %}

{% block content %}

  <h4>{{obj.chatUuid}}</h4>
  <h3>In private chat</h3>
    <p>Send Message to <b>{{personobj.username}}</b></p>
    
    <form action = "." method='post'id="form"> 
      <input type="text" name="message" />
    </form>
  <div id = "messages">
    {% for message in chats %}
       {% if message.sender.id == request.user.id %}
          <div class="sent">
            <p class="message">{{message.message}}</p> 
          </div>
        {% else%}
          <div class="received">
            <p class="message">{{message.message}}</p> 
          </div>
        {% endif %}
    {% endfor %}
  </div>

  <script type = "text/javascript">
      let chatUuid = "{{obj.chatUuid}}";
      let currentuser = "{{request.user.id}}"
      let url = `ws://${window.location.host}/ws/socket-server/`+chatUuid+`/`;
      // let url = `ws://${window.location.host}/ws/socket-server/`;
      
      console.log("url: ",url);
      const chatSocket = new WebSocket(url)

      chatSocket.onmessage = function(e){
          let data = JSON.parse(e.data)
          console.log('Data: ', data)
          let sender = data.user_id
          if(data.type === 'chat'){
              console.log("In chats")
              let messages = document.getElementById('messages')
              console.log("current user: ",currentuser);
              console.log("sender: ",sender)
              if( currentuser == sender){
                  messages.insertAdjacentHTML('beforeend',`
                <div class="sent">
                  <p class="message">${data.message}</p> 
                </div>
                `)   
              }else{
                messages.insertAdjacentHTML('beforeend',`
              <div class="received">
                <p class="message">${data.message}</p> 
              </div>
              `)
              }
          }
      }
    
      let form = document.getElementById('form')
      form.addEventListener('submit', (e)=>{
          e.preventDefault()
          let message = e.target.message.value;
          chatSocket.send(JSON.stringify({
              'message':message
          }))
          form.reset()
      })
    </script>

{% endblock %}

chat/templates/chat/chatrooms.html
{% extends 'chat/lobby.html' %}

{% block content %}
   <ul>
    {{user}}
    {% for obj in objs %}
     <li><a href="{% url 'chat:get_chatroom' obj.chatUuid %}">
        {% if obj.user1 != user %}
            {{ obj.user1 }}
        {% elif obj.user2 != user %}
            {{ obj.user2 }}
        {% endif %}
    </a></li>
    {% endfor %}
   </ul>
{% endblock %}

chat/templates/chat/list.html
{% extends 'chat/lobby.html' %}

{% block content %}
    <h1>{{user}}</h1>
    <h3>In list</h3>
   <ul>
    {% for obj in objs %}
     <li><a href="{% url 'chat:create_chatroom' obj.pk %}">

        {{ obj.username }}</a></li>
    {% endfor %}
   </ul>
{% endblock %}

chat/templates/chat/lobby.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '../static/chat/styles.css' %}">
    <title>Lobby</title>
</head>
<body>
    <h1>Let's Chat</h1>
    {% block content %}
      
    {% endblock %}
    
        
</body>
</html>